apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aurora
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kevinfinalboss/argocd-projects.git"
    targetRevision: HEAD
    path: "charts/application-template"
    helm:
      values: |-
        replicaCount: 1

        image:
          repository: docker.io/kevinfinalboss/aurorabot
          tag: v1.0.0
          pullPolicy: IfNotPresent

        containerPort: 80

        service:
          type: ClusterIP
          port: 80

        env:  
          - name: APP_NAME
            value: "aurora"

        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"

        volumes:
          - name: app-storage
            emptyDir: {}

        volumeMounts:
          - name: app-storage
            mountPath: /app
            subPath: ""

        initContainers:
          - name: init-dirs
            image: busybox:1.35
            command: ['sh', '-c', 'mkdir -p /app/data /app/logs /app/config']
            volumeMounts:
              - name: app-storage
                mountPath: /app

        nodeSelector: {}
        tolerations: []
        affinity: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: bot
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true