apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aurorabot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kevinfinalboss/argocd-projects.git"
    targetRevision: HEAD
    path: "charts/applications"
    helm:
      values: |-
        replicaCount: 1

        image:
          repository: docker.io/kevinfinalboss/aurorabot
          tag: v1.0.0
          pullPolicy: IfNotPresent

        containerPort: 80

        service:
          type: ClusterIP
          port: 80

        env:  # Adicionado para configurações específicas do Aurora
          - name: APP_NAME
            value: "aurora"
          # Adicione outras variáveis de ambiente necessárias

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

        nodeSelector: {}
        tolerations: []
        affinity: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true