apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lavalink
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kevinfinalboss/argocd-projects.git
    targetRevision: HEAD
    path: charts/application-template
    helm:
      values: |-
        replicaCount: 1
        
        image:
          repository: docker.io/kevinfinalboss/lavalink
          tag: latest
          pullPolicy: Always
        
        nameOverride: "lavalink"
        fullnameOverride: "lavalink"
        
        containerPort: 2333
        
        service:
          type: ClusterIP
          port: 2333
          nodePort: null

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "TCP"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            cert-manager.io/cluster-issuer: "letsencrypt-dns"
            external-dns.alpha.kubernetes.io/hostname: "lavalink.kevindev.com.br"
            external-dns.alpha.kubernetes.io/target: "147.93.69.150"
          hosts:
            - host: lavalink.kevindev.com.br
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "lavalink.kevindev.com.br"
              secretName: "lavalink-server-tls"
        
        persistence:
          enabled: true
          storageClass: "longhorn"
          accessMode: ReadWriteOnce
          size: 1Gi
          annotations: {}
        
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            memory: 512Mi
            cpu: 500m

        externalSecrets:
          enabled: true
          mountAsFile: true
          mountAsEnv: false
          parameters:
            - name: config
              path: /eks/bot/lavalink/config
              key: application.yml
              mountPath: /opt/lavalink/application.yml

        volumes:
          - name: logs
            persistentVolumeClaim:
              claimName: lavalink-data
          - name: plugins
            persistentVolumeClaim:
              claimName: lavalink-data
        
        volumeMounts:
          - name: logs
            mountPath: /opt/lavalink/logs
            subPath: logs
          - name: plugins
            mountPath: /opt/lavalink/plugins
            subPath: plugins

        initContainers:
          - name: init-dirs
            image: busybox:1.35
            command:
              - sh
              - -c
              - |
                mkdir -p /opt/lavalink/logs /opt/lavalink/plugins &&
                chmod -R 777 /opt/lavalink
            volumeMounts:
              - name: logs
                mountPath: /opt/lavalink/logs
                subPath: logs
              - name: plugins
                mountPath: /opt/lavalink/plugins
                subPath: plugins

        env:
          - name: SERVER_PORT
            value: "2333"
          - name: SERVER_ADDRESS
            value: "0.0.0.0"
          - name: JAVA_OPTS
            value: "-Xmx700M -Xms300M -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled"
        
        nodeSelector: {}
        tolerations: []
        affinity: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: lavalink
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true