apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-master
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kevinfinalboss/argocd-projects.git
    targetRevision: HEAD
    path: applications
    directory:
      recurse: true
      exclude: '*/templates/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true