apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/kevinfinalboss/argocd-projects.git"
        revision: HEAD
        directories:
          - path: "applications/*"
  template:
    metadata:
      name: '{{- replace "/" "-" .path.basename | lower -}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/kevinfinalboss/argocd-projects.git"
        targetRevision: HEAD
        path: "{{ .path }}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{- replace "/" "-" .path.basename | lower -}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true