replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80
  nodePort: null

env: []
# - name: VARIABLE
#   value: "value"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}